/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Product;
import javax.swing.JOptionPane;
import Business.ProductDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author info
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    private final ProductDirectory prodDir;
    private final Product product;
    private final JPanel rightPanel;

    ViewPanel(JPanel rightPanel, Product prod, ProductDirectory prodDir) {
        initComponents();
        this.rightPanel = rightPanel;
        this.product = prod;
        txtAvailablity.setText(String.valueOf(prod.getAvailNum()));
        txtPrice.setText(String.valueOf(prod.getPrice()));
        txtProdName.setText(prod.getName());
        txtDesc.setText(prod.getDescription());
        txtAvailablity.setEnabled(false);
        txtPrice.setEnabled(false);
        txtProdName.setEnabled(false);
        txtDesc.setEnabled(false);
        this.prodDir = prodDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPrice = new javax.swing.JTextField();
        txtProdName = new javax.swing.JTextField();
        txtAvailablity = new javax.swing.JTextField();
        lblBankName = new javax.swing.JLabel();
        lblRoutingNo = new javax.swing.JLabel();
        lblAccNo = new javax.swing.JLabel();
        lblHead = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrice.setEditable(false);
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 128, 83, -1));

        txtProdName.setEditable(false);
        add(txtProdName, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 40, 83, -1));

        txtAvailablity.setEditable(false);
        add(txtAvailablity, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 84, 83, -1));

        lblBankName.setText("Price");
        add(lblBankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 131, -1, -1));

        lblRoutingNo.setText("Product Name");
        add(lblRoutingNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 43, -1, -1));

        lblAccNo.setText("Availablity");
        add(lblAccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 90, 100, 14));

        lblHead.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHead.setText("View Product");
        add(lblHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 0, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 218, -1, -1));

        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 218, 100, -1));

        jLabel1.setText("Description");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 175, -1, -1));
        add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 172, 83, -1));

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtAvailablity.setEnabled(true);
        txtPrice.setEnabled(true);
        txtProdName.setEnabled(true);
        txtDesc.setEnabled(true);
        txtAvailablity.setEditable(true);
        txtPrice.setEditable(true);
        txtProdName.setEditable(true);
        txtDesc.setEditable(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        try {
            double price = Double.parseDouble(txtPrice.getText());
            int availability = Integer.parseInt(txtAvailablity.getText());

            product.setName(txtProdName.getText());
            product.setPrice(price);
            product.setAvailNum(availability);
            product.setDescription(txtDesc.getText());
            JOptionPane.showMessageDialog(null, "Account updated successfully");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Only Numbers allowed in Price and Avalibility");

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
        Component[] components = rightPanel.getComponents();
        for (Component c : components) {
            if (c instanceof ManageProdPanel) {
                ManageProdPanel panel = (ManageProdPanel) c;
                panel.populate();
            }
        }
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblHead;
    private javax.swing.JLabel lblRoutingNo;
    private javax.swing.JTextField txtAvailablity;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProdName;
    // End of variables declaration//GEN-END:variables
}
